platform :ios, '16.0'

target 'Luma' do
  use_frameworks!
  pod 'AEPCore', '~> 3'
  pod 'AEPEdge', '~> 1'
  pod 'AEPEdgeConsent', '~> 1'
  pod 'AEPEdgeIdentity', '~> 1'
  pod 'AEPUserProfile', '~> 3'
  pod 'AEPAssurance', '~> 3'
  pod 'AEPServices', '~> 3'
  pod 'AEPLifecycle', '~> 3'
  pod 'AEPMessaging', '~> 1'
  pod 'AEPSignal', '~> 3'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Apollo'
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
  
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'ARCHS'
      end
    end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "16.0"
     end
  end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
  end
end
